/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 32.6.3 Wed Feb 20 12:39:08 2019.
 */

#include <string.h>

#include "lynx19gw.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int lynx19gw_as_torque_req_pack(
    uint8_t *dst_p,
    const struct lynx19gw_as_torque_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->torque_set_point_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->torque_set_point_left, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->torque_set_point_right, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->torque_set_point_right, 8u, 0xffu);

    return (8);
}

int lynx19gw_as_torque_req_unpack(
    struct lynx19gw_as_torque_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->torque_set_point_left |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->torque_set_point_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->torque_set_point_right |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->torque_set_point_right |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_as_torque_req_torque_set_point_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_as_torque_req_torque_set_point_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_as_torque_req_torque_set_point_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_as_torque_req_torque_set_point_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_as_torque_req_torque_set_point_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_as_torque_req_torque_set_point_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_as_dl_sensors_pack(
    uint8_t *dst_p,
    const struct lynx19gw_as_dl_sensors_t *src_p,
    size_t size)
{
    uint8_t as_rtd;
    uint8_t pressure_regulator;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->as_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->steering_position, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->rack_position, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->pressure_ebs_act, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->pressure_ebs_line, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->pressure_service, 0u, 0xffu);
    pressure_regulator = (uint8_t)src_p->pressure_regulator;
    dst_p[6] |= pack_left_shift_u8(pressure_regulator, 0u, 0xffu);
    as_rtd = (uint8_t)src_p->as_rtd;
    dst_p[7] |= pack_left_shift_u8(as_rtd, 0u, 0xffu);

    return (8);
}

int lynx19gw_as_dl_sensors_unpack(
    struct lynx19gw_as_dl_sensors_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t as_rtd;
    uint8_t pressure_regulator;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->as_state |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->steering_position |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->rack_position |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->pressure_ebs_act |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->pressure_ebs_line |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->pressure_service |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    pressure_regulator = 0u;
    pressure_regulator |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->pressure_regulator = (int8_t)pressure_regulator;
    as_rtd = 0u;
    as_rtd |= unpack_right_shift_u8(src_p[7], 0u, 0xffu);
    dst_p->as_rtd = (int8_t)as_rtd;

    return (0);
}

uint8_t lynx19gw_as_dl_sensors_as_state_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_as_dl_sensors_as_state_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_as_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_as_dl_sensors_steering_position_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_as_dl_sensors_steering_position_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_steering_position_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_as_dl_sensors_rack_position_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_as_dl_sensors_rack_position_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_rack_position_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_as_dl_sensors_pressure_ebs_act_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_as_dl_sensors_pressure_ebs_act_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_pressure_ebs_act_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_as_dl_sensors_pressure_ebs_line_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_as_dl_sensors_pressure_ebs_line_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_pressure_ebs_line_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_as_dl_sensors_pressure_service_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_as_dl_sensors_pressure_service_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_pressure_service_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int8_t lynx19gw_as_dl_sensors_pressure_regulator_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_as_dl_sensors_pressure_regulator_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_pressure_regulator_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t lynx19gw_as_dl_sensors_as_rtd_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_as_dl_sensors_as_rtd_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_as_dl_sensors_as_rtd_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_dl_sensors_4_new_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_sensors_4_new_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int lynx19gw_nr_dl_sensors_4_new_unpack(
    struct lynx19gw_nr_dl_sensors_4_new_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int lynx19gw_nr_dl_tv_out_3_new_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_tv_out_3_new_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int lynx19gw_nr_dl_tv_out_3_new_unpack(
    struct lynx19gw_nr_dl_tv_out_3_new_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int lynx19gw_dl_as_status_pack(
    uint8_t *dst_p,
    const struct lynx19gw_dl_as_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->as_mission, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->brake_front, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_rear, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->dl_status, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->acc_so_c, 0u, 0xffu);

    return (8);
}

int lynx19gw_dl_as_status_unpack(
    struct lynx19gw_dl_as_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->as_mission |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_front |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_rear |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->dl_status |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->acc_so_c |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_dl_as_status_as_mission_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_as_status_as_mission_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_as_status_as_mission_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_as_status_brake_front_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_as_status_brake_front_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_as_status_brake_front_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_as_status_brake_rear_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_as_status_brake_rear_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_as_status_brake_rear_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_as_status_dl_status_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_as_status_dl_status_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_as_status_dl_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_as_status_acc_so_c_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_as_status_acc_so_c_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_as_status_acc_so_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_dl_tv_out_2_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_tv_out_2_t *src_p,
    size_t size)
{
    uint16_t tv_out_yaw_rate_ref;
    uint8_t tv_out_sw_ang;
    uint8_t tv_out_tv_l_act;
    uint8_t tv_out_tv_r_act;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->tv_out_mu, 0u, 0xffu);
    tv_out_sw_ang = (uint8_t)src_p->tv_out_sw_ang;
    dst_p[1] |= pack_left_shift_u8(tv_out_sw_ang, 0u, 0xffu);
    tv_out_tv_l_act = (uint8_t)src_p->tv_out_tv_l_act;
    dst_p[2] |= pack_left_shift_u8(tv_out_tv_l_act, 0u, 0xffu);
    tv_out_tv_r_act = (uint8_t)src_p->tv_out_tv_r_act;
    dst_p[3] |= pack_left_shift_u8(tv_out_tv_r_act, 0u, 0xffu);
    tv_out_yaw_rate_ref = (uint16_t)src_p->tv_out_yaw_rate_ref;
    dst_p[4] |= pack_left_shift_u16(tv_out_yaw_rate_ref, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(tv_out_yaw_rate_ref, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->tv_out_yrc_act, 0u, 0xffu);

    return (7);
}

int lynx19gw_nr_dl_tv_out_2_unpack(
    struct lynx19gw_nr_dl_tv_out_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tv_out_yaw_rate_ref;
    uint8_t tv_out_sw_ang;
    uint8_t tv_out_tv_l_act;
    uint8_t tv_out_tv_r_act;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->tv_out_mu |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    tv_out_sw_ang = 0u;
    tv_out_sw_ang |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->tv_out_sw_ang = (int8_t)tv_out_sw_ang;
    tv_out_tv_l_act = 0u;
    tv_out_tv_l_act |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->tv_out_tv_l_act = (int8_t)tv_out_tv_l_act;
    tv_out_tv_r_act = 0u;
    tv_out_tv_r_act |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->tv_out_tv_r_act = (int8_t)tv_out_tv_r_act;
    tv_out_yaw_rate_ref = 0u;
    tv_out_yaw_rate_ref |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    tv_out_yaw_rate_ref |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->tv_out_yaw_rate_ref = (int16_t)tv_out_yaw_rate_ref;
    dst_p->tv_out_yrc_act |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nr_dl_tv_out_2_tv_out_mu_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double lynx19gw_nr_dl_tv_out_2_tv_out_mu_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool lynx19gw_nr_dl_tv_out_2_tv_out_mu_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int8_t lynx19gw_nr_dl_tv_out_2_tv_out_sw_ang_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_nr_dl_tv_out_2_tv_out_sw_ang_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_2_tv_out_sw_ang_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t lynx19gw_nr_dl_tv_out_2_tv_out_tv_l_act_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_nr_dl_tv_out_2_tv_out_tv_l_act_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_2_tv_out_tv_l_act_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t lynx19gw_nr_dl_tv_out_2_tv_out_tv_r_act_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_nr_dl_tv_out_2_tv_out_tv_r_act_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_2_tv_out_tv_r_act_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_nr_dl_tv_out_2_tv_out_yaw_rate_ref_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double lynx19gw_nr_dl_tv_out_2_tv_out_yaw_rate_ref_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool lynx19gw_nr_dl_tv_out_2_tv_out_yaw_rate_ref_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nr_dl_tv_out_2_tv_out_yrc_act_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_tv_out_2_tv_out_yrc_act_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_2_tv_out_yrc_act_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_dl_tv_out_1_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_tv_out_1_t *src_p,
    size_t size)
{
    uint16_t tv_out_fz_rl;
    uint16_t tv_out_fz_rr;
    uint16_t tv_out_mz_req;
    uint16_t tv_out_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tv_out_fz_rl = (uint16_t)src_p->tv_out_fz_rl;
    dst_p[0] |= pack_left_shift_u16(tv_out_fz_rl, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(tv_out_fz_rl, 8u, 0xffu);
    tv_out_fz_rr = (uint16_t)src_p->tv_out_fz_rr;
    dst_p[2] |= pack_left_shift_u16(tv_out_fz_rr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(tv_out_fz_rr, 8u, 0xffu);
    tv_out_mz_req = (uint16_t)src_p->tv_out_mz_req;
    dst_p[4] |= pack_left_shift_u16(tv_out_mz_req, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(tv_out_mz_req, 8u, 0xffu);
    tv_out_velocity = (uint16_t)src_p->tv_out_velocity;
    dst_p[6] |= pack_left_shift_u16(tv_out_velocity, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(tv_out_velocity, 8u, 0xffu);

    return (8);
}

int lynx19gw_nr_dl_tv_out_1_unpack(
    struct lynx19gw_nr_dl_tv_out_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tv_out_fz_rl;
    uint16_t tv_out_fz_rr;
    uint16_t tv_out_mz_req;
    uint16_t tv_out_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    tv_out_fz_rl = 0u;
    tv_out_fz_rl |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    tv_out_fz_rl |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->tv_out_fz_rl = (int16_t)tv_out_fz_rl;
    tv_out_fz_rr = 0u;
    tv_out_fz_rr |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    tv_out_fz_rr |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->tv_out_fz_rr = (int16_t)tv_out_fz_rr;
    tv_out_mz_req = 0u;
    tv_out_mz_req |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    tv_out_mz_req |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->tv_out_mz_req = (int16_t)tv_out_mz_req;
    tv_out_velocity = 0u;
    tv_out_velocity |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    tv_out_velocity |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->tv_out_velocity = (int16_t)tv_out_velocity;

    return (0);
}

int16_t lynx19gw_nr_dl_tv_out_1_tv_out_fz_rl_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_nr_dl_tv_out_1_tv_out_fz_rl_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_1_tv_out_fz_rl_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_nr_dl_tv_out_1_tv_out_fz_rr_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_nr_dl_tv_out_1_tv_out_fz_rr_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_1_tv_out_fz_rr_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_nr_dl_tv_out_1_tv_out_mz_req_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double lynx19gw_nr_dl_tv_out_1_tv_out_mz_req_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool lynx19gw_nr_dl_tv_out_1_tv_out_mz_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_nr_dl_tv_out_1_tv_out_velocity_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_nr_dl_tv_out_1_tv_out_velocity_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_tv_out_1_tv_out_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_dl_nr_tv_conf_2_pack(
    uint8_t *dst_p,
    const struct lynx19gw_dl_nr_tv_conf_2_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->tv_lltd_ay_scaling, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->tv_tc_delta_th, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->tv_tc_kgain, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->tv_yrc_kbias, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->tv_yrc_os_agr, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->tv_tv_mode, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->tv_switches, 0u, 0xffu);

    return (7);
}

int lynx19gw_dl_nr_tv_conf_2_unpack(
    struct lynx19gw_dl_nr_tv_conf_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->tv_lltd_ay_scaling |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->tv_tc_delta_th |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->tv_tc_kgain |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->tv_yrc_kbias |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->tv_yrc_os_agr |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->tv_tv_mode |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->tv_switches |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_lltd_ay_scaling_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_lltd_ay_scaling_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_lltd_ay_scaling_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_tc_delta_th_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_tc_delta_th_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_tc_delta_th_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_tc_kgain_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_tc_kgain_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_tc_kgain_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_yrc_kbias_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_yrc_kbias_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_yrc_kbias_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_yrc_os_agr_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_yrc_os_agr_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_yrc_os_agr_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_tv_mode_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_tv_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_tv_mode_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_dl_nr_tv_conf_2_tv_switches_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_dl_nr_tv_conf_2_tv_switches_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_2_tv_switches_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_dl_nr_tv_conf_1_pack(
    uint8_t *dst_p,
    const struct lynx19gw_dl_nr_tv_conf_1_t *src_p,
    size_t size)
{
    uint16_t tv_ku_stat;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tv_ku_stat = (uint16_t)src_p->tv_ku_stat;
    dst_p[0] |= pack_left_shift_u16(tv_ku_stat, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(tv_ku_stat, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->tv_pid_kp_scale, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->tv_pid_kp_scale, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->tv_pid_kd_scale, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->tv_pid_kd_scale, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->tv_pid_tt_scale, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->tv_pid_tt_scale, 8u, 0xffu);

    return (8);
}

int lynx19gw_dl_nr_tv_conf_1_unpack(
    struct lynx19gw_dl_nr_tv_conf_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tv_ku_stat;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    tv_ku_stat = 0u;
    tv_ku_stat |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    tv_ku_stat |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->tv_ku_stat = (int16_t)tv_ku_stat;
    dst_p->tv_pid_kp_scale |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->tv_pid_kp_scale |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->tv_pid_kd_scale |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->tv_pid_kd_scale |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->tv_pid_tt_scale |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->tv_pid_tt_scale |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int16_t lynx19gw_dl_nr_tv_conf_1_tv_ku_stat_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_dl_nr_tv_conf_1_tv_ku_stat_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_dl_nr_tv_conf_1_tv_ku_stat_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_dl_nr_tv_conf_1_tv_pid_kp_scale_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double lynx19gw_dl_nr_tv_conf_1_tv_pid_kp_scale_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool lynx19gw_dl_nr_tv_conf_1_tv_pid_kp_scale_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_dl_nr_tv_conf_1_tv_pid_kd_scale_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double lynx19gw_dl_nr_tv_conf_1_tv_pid_kd_scale_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool lynx19gw_dl_nr_tv_conf_1_tv_pid_kd_scale_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_dl_nr_tv_conf_1_tv_pid_tt_scale_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double lynx19gw_dl_nr_tv_conf_1_tv_pid_tt_scale_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool lynx19gw_dl_nr_tv_conf_1_tv_pid_tt_scale_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_per_pdo_1_tx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_per_pdo_1_tx_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->drive_engaged_right, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_estimate_right, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_estimate_right, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_estimate_right, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_estimate_right, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->errors_right, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->errors_right, 8u, 0xffu);

    return (7);
}

int lynx19gw_per_pdo_1_tx_unpack(
    struct lynx19gw_per_pdo_1_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->drive_engaged_right |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_estimate_right |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_estimate_right |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_estimate_right |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_estimate_right |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->errors_right |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->errors_right |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_per_pdo_1_tx_drive_engaged_right_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_per_pdo_1_tx_drive_engaged_right_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_1_tx_drive_engaged_right_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_per_pdo_1_tx_torque_estimate_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_1_tx_torque_estimate_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_1_tx_torque_estimate_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_per_pdo_1_tx_speed_estimate_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_1_tx_speed_estimate_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_1_tx_speed_estimate_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_per_pdo_1_tx_errors_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_1_tx_errors_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_1_tx_errors_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_per_pdo_2_tx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_per_pdo_2_tx_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->measured_udc_right, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->measured_udc_right, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->power_estimate_right, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->power_estimate_right, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->temperature_windings_right, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->temperature_windings_right, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->temperature_inverter_right, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->temperature_inverter_right, 8u, 0xffu);

    return (8);
}

int lynx19gw_per_pdo_2_tx_unpack(
    struct lynx19gw_per_pdo_2_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->measured_udc_right |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->measured_udc_right |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->power_estimate_right |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->power_estimate_right |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temperature_windings_right |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->temperature_windings_right |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->temperature_inverter_right |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->temperature_inverter_right |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_per_pdo_2_tx_measured_udc_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_2_tx_measured_udc_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_2_tx_measured_udc_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_per_pdo_2_tx_power_estimate_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_2_tx_power_estimate_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_2_tx_power_estimate_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_per_pdo_2_tx_temperature_windings_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_2_tx_temperature_windings_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_2_tx_temperature_windings_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_per_pdo_2_tx_temperature_inverter_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_per_pdo_2_tx_temperature_inverter_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_per_pdo_2_tx_temperature_inverter_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_pel_pdo_2_tx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_pel_pdo_2_tx_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->power_estimate_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->power_estimate_left, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->measured_udc_left, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->measured_udc_left, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->temperature_windings_left, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->temperature_windings_left, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->temperature_inverter_left, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->temperature_inverter_left, 8u, 0xffu);

    return (8);
}

int lynx19gw_pel_pdo_2_tx_unpack(
    struct lynx19gw_pel_pdo_2_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->power_estimate_left |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->power_estimate_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->measured_udc_left |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->measured_udc_left |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temperature_windings_left |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->temperature_windings_left |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->temperature_inverter_left |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->temperature_inverter_left |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_pel_pdo_2_tx_power_estimate_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_2_tx_power_estimate_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_2_tx_power_estimate_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_pel_pdo_2_tx_measured_udc_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_2_tx_measured_udc_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_2_tx_measured_udc_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_pel_pdo_2_tx_temperature_windings_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_2_tx_temperature_windings_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_2_tx_temperature_windings_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_pel_pdo_2_tx_temperature_inverter_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_2_tx_temperature_inverter_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_2_tx_temperature_inverter_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_pel_pdo_1_tx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_pel_pdo_1_tx_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->drive_engaged_left, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_estimate_left, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_estimate_left, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_estimate_left, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_estimate_left, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->errors_left, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->errors_left, 8u, 0xffu);

    return (7);
}

int lynx19gw_pel_pdo_1_tx_unpack(
    struct lynx19gw_pel_pdo_1_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->drive_engaged_left |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_estimate_left |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_estimate_left |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_estimate_left |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_estimate_left |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->errors_left |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->errors_left |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_pel_pdo_1_tx_drive_engaged_left_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_pel_pdo_1_tx_drive_engaged_left_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_1_tx_drive_engaged_left_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_pel_pdo_1_tx_torque_estimate_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_1_tx_torque_estimate_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_1_tx_torque_estimate_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_pel_pdo_1_tx_speed_estimate_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_1_tx_speed_estimate_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_1_tx_speed_estimate_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_pel_pdo_1_tx_errors_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_pel_pdo_1_tx_errors_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_pel_pdo_1_tx_errors_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_per_pdo_2_rx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_per_pdo_2_rx_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->enable_drive_right, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_set_point_right, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_set_point_right, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_limit_right, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_limit_right, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->error_reset_right, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->error_reset_right, 8u, 0xffu);

    return (7);
}

int lynx19gw_nr_per_pdo_2_rx_unpack(
    struct lynx19gw_nr_per_pdo_2_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->enable_drive_right |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_set_point_right |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_set_point_right |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_limit_right |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_limit_right |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->error_reset_right |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->error_reset_right |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nr_per_pdo_2_rx_enable_drive_right_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_per_pdo_2_rx_enable_drive_right_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_2_rx_enable_drive_right_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_per_pdo_2_rx_torque_set_point_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_per_pdo_2_rx_torque_set_point_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_2_rx_torque_set_point_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_per_pdo_2_rx_speed_limit_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_per_pdo_2_rx_speed_limit_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_2_rx_speed_limit_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_per_pdo_2_rx_error_reset_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_per_pdo_2_rx_error_reset_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_2_rx_error_reset_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_pel_pdo_2_rx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_pel_pdo_2_rx_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->enable_drive_left, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_set_point_left, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_set_point_left, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_limit_left, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_limit_left, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->error_reset_left, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->error_reset_left, 8u, 0xffu);

    return (7);
}

int lynx19gw_nr_pel_pdo_2_rx_unpack(
    struct lynx19gw_nr_pel_pdo_2_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->enable_drive_left |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_set_point_left |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_set_point_left |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_limit_left |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_limit_left |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->error_reset_left |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->error_reset_left |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nr_pel_pdo_2_rx_enable_drive_left_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_pel_pdo_2_rx_enable_drive_left_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_2_rx_enable_drive_left_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_pel_pdo_2_rx_torque_set_point_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_pel_pdo_2_rx_torque_set_point_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_2_rx_torque_set_point_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_pel_pdo_2_rx_speed_limit_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_pel_pdo_2_rx_speed_limit_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_2_rx_speed_limit_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_pel_pdo_2_rx_error_reset_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_pel_pdo_2_rx_error_reset_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_2_rx_error_reset_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_per_pdo_1_rx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_per_pdo_1_rx_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->enable_drive_right, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_set_point_right, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_set_point_right, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_limit_right, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_limit_right, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->error_reset_right, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->error_reset_right, 8u, 0xffu);

    return (7);
}

int lynx19gw_nr_per_pdo_1_rx_unpack(
    struct lynx19gw_nr_per_pdo_1_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->enable_drive_right |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_set_point_right |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_set_point_right |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_limit_right |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_limit_right |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->error_reset_right |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->error_reset_right |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nr_per_pdo_1_rx_enable_drive_right_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_per_pdo_1_rx_enable_drive_right_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_1_rx_enable_drive_right_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_per_pdo_1_rx_torque_set_point_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_per_pdo_1_rx_torque_set_point_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_1_rx_torque_set_point_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_per_pdo_1_rx_speed_limit_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_per_pdo_1_rx_speed_limit_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_1_rx_speed_limit_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_per_pdo_1_rx_error_reset_right_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_per_pdo_1_rx_error_reset_right_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_per_pdo_1_rx_error_reset_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_client_bms_data_pack(
    uint8_t *dst_p,
    const struct lynx19gw_client_bms_data_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->enable_communication, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->trigger_imd, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->trigger_bms, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_reset, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_discharge, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->bms_discharge_threshold, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->bms_discharge_threshold, 8u, 0xffu);

    return (7);
}

int lynx19gw_client_bms_data_unpack(
    struct lynx19gw_client_bms_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->enable_communication |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->trigger_imd |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->trigger_bms |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->bms_reset |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->bms_discharge |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bms_discharge_threshold |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->bms_discharge_threshold |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_client_bms_data_enable_communication_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_client_bms_data_enable_communication_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_client_bms_data_enable_communication_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_client_bms_data_trigger_imd_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_client_bms_data_trigger_imd_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_client_bms_data_trigger_imd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_client_bms_data_trigger_bms_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_client_bms_data_trigger_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_client_bms_data_trigger_bms_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_client_bms_data_bms_reset_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_client_bms_data_bms_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_client_bms_data_bms_reset_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_client_bms_data_bms_discharge_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_client_bms_data_bms_discharge_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_client_bms_data_bms_discharge_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_client_bms_data_bms_discharge_threshold_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_client_bms_data_bms_discharge_threshold_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_client_bms_data_bms_discharge_threshold_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_bms_client_cell_temperatures_pack(
    uint8_t *dst_p,
    const struct lynx19gw_bms_client_cell_temperatures_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->bms_temparature_payload_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_temparature_payload_id, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->bms_temparature_payload_1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->bms_temparature_payload_1, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->bms_temparature_payload_2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->bms_temparature_payload_2, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->bms_temparature_payload_3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->bms_temparature_payload_3, 8u, 0xffu);

    return (8);
}

int lynx19gw_bms_client_cell_temperatures_unpack(
    struct lynx19gw_bms_client_cell_temperatures_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->bms_temparature_payload_id |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->bms_temparature_payload_id |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->bms_temparature_payload_1 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->bms_temparature_payload_1 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->bms_temparature_payload_2 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->bms_temparature_payload_2 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->bms_temparature_payload_3 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->bms_temparature_payload_3 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_id_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_id_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_1_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_1_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_2_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_2_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_3_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_3_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_temperatures_bms_temparature_payload_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_bms_client_cell_voltages_pack(
    uint8_t *dst_p,
    const struct lynx19gw_bms_client_cell_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->bms_voltage_payload_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_voltage_payload_id, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->bms_voltage_payload_1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->bms_voltage_payload_1, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->bms_voltage_payload_2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->bms_voltage_payload_2, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->bms_voltage_payload_3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->bms_voltage_payload_3, 8u, 0xffu);

    return (8);
}

int lynx19gw_bms_client_cell_voltages_unpack(
    struct lynx19gw_bms_client_cell_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->bms_voltage_payload_id |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->bms_voltage_payload_id |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->bms_voltage_payload_1 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->bms_voltage_payload_1 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->bms_voltage_payload_2 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->bms_voltage_payload_2 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->bms_voltage_payload_3 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->bms_voltage_payload_3 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_bms_client_cell_voltages_bms_voltage_payload_id_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_voltages_bms_voltage_payload_id_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_voltages_bms_voltage_payload_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_client_cell_voltages_bms_voltage_payload_1_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_voltages_bms_voltage_payload_1_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_voltages_bms_voltage_payload_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_client_cell_voltages_bms_voltage_payload_2_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_voltages_bms_voltage_payload_2_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_voltages_bms_voltage_payload_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_client_cell_voltages_bms_voltage_payload_3_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_client_cell_voltages_bms_voltage_payload_3_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_client_cell_voltages_bms_voltage_payload_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nf_dl_buttons_rtd_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nf_dl_buttons_rtd_t *src_p,
    size_t size)
{
    uint8_t redy_to_drive;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->buttons, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->knob_l, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->knob_r, 0u, 0xffu);
    redy_to_drive = (uint8_t)src_p->redy_to_drive;
    dst_p[3] |= pack_left_shift_u8(redy_to_drive, 0u, 0xffu);

    return (4);
}

int lynx19gw_nf_dl_buttons_rtd_unpack(
    struct lynx19gw_nf_dl_buttons_rtd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t redy_to_drive;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->buttons |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->knob_l |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->knob_r |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    redy_to_drive = 0u;
    redy_to_drive |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->redy_to_drive = (int8_t)redy_to_drive;

    return (0);
}

uint8_t lynx19gw_nf_dl_buttons_rtd_buttons_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_dl_buttons_rtd_buttons_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_dl_buttons_rtd_buttons_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nf_dl_buttons_rtd_knob_l_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_dl_buttons_rtd_knob_l_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_dl_buttons_rtd_knob_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nf_dl_buttons_rtd_knob_r_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_dl_buttons_rtd_knob_r_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_dl_buttons_rtd_knob_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int8_t lynx19gw_nf_dl_buttons_rtd_redy_to_drive_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_nf_dl_buttons_rtd_redy_to_drive_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_dl_buttons_rtd_redy_to_drive_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_datalogger_config_pack(
    uint8_t *dst_p,
    const struct lynx19gw_datalogger_config_t *src_p,
    size_t size)
{
    uint16_t config_payload_1;
    uint16_t config_payload_2;
    uint16_t config_payload_3;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->config_id, 0u, 0xffu);
    config_payload_1 = (uint16_t)src_p->config_payload_1;
    dst_p[1] |= pack_left_shift_u16(config_payload_1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(config_payload_1, 8u, 0xffu);
    config_payload_2 = (uint16_t)src_p->config_payload_2;
    dst_p[3] |= pack_left_shift_u16(config_payload_2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(config_payload_2, 8u, 0xffu);
    config_payload_3 = (uint16_t)src_p->config_payload_3;
    dst_p[5] |= pack_left_shift_u16(config_payload_3, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(config_payload_3, 8u, 0xffu);

    return (8);
}

int lynx19gw_datalogger_config_unpack(
    struct lynx19gw_datalogger_config_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t config_payload_1;
    uint16_t config_payload_2;
    uint16_t config_payload_3;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->config_id |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    config_payload_1 = 0u;
    config_payload_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    config_payload_1 |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->config_payload_1 = (int16_t)config_payload_1;
    config_payload_2 = 0u;
    config_payload_2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    config_payload_2 |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->config_payload_2 = (int16_t)config_payload_2;
    config_payload_3 = 0u;
    config_payload_3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    config_payload_3 |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->config_payload_3 = (int16_t)config_payload_3;

    return (0);
}

uint8_t lynx19gw_datalogger_config_config_id_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_datalogger_config_config_id_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_datalogger_config_config_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_datalogger_config_config_payload_1_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_datalogger_config_config_payload_1_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_datalogger_config_config_payload_1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_datalogger_config_config_payload_2_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_datalogger_config_config_payload_2_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_datalogger_config_config_payload_2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_datalogger_config_config_payload_3_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_datalogger_config_config_payload_3_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_datalogger_config_config_payload_3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_bms_dl_hartbeat_pack(
    uint8_t *dst_p,
    const struct lynx19gw_bms_dl_hartbeat_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->bms_status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_status, 8u, 0xffu);

    return (8);
}

int lynx19gw_bms_dl_hartbeat_unpack(
    struct lynx19gw_bms_dl_hartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->bms_status |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->bms_status |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_bms_dl_hartbeat_bms_status_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_dl_hartbeat_bms_status_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_dl_hartbeat_bms_status_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_dl_hartbeat_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_hartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->node_2_status, 0u, 0xffu);

    return (1);
}

int lynx19gw_nr_dl_hartbeat_unpack(
    struct lynx19gw_nr_dl_hartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->node_2_status |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nr_dl_hartbeat_node_2_status_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_hartbeat_node_2_status_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_hartbeat_node_2_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nf_dl_hartbeat_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nf_dl_hartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->node_1_status, 0u, 0xffu);

    return (1);
}

int lynx19gw_nf_dl_hartbeat_unpack(
    struct lynx19gw_nf_dl_hartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->node_1_status |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nf_dl_hartbeat_node_1_status_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_dl_hartbeat_node_1_status_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_dl_hartbeat_node_1_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_bms_dl_data_pack(
    uint8_t *dst_p,
    const struct lynx19gw_bms_dl_data_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->accumulator_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->accumulator_current, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->accumulator_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->accumulator_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->accumulator_so_c, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->accumulator_so_c, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->accumulator_temp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->accumulator_temp, 8u, 0xffu);

    return (8);
}

int lynx19gw_bms_dl_data_unpack(
    struct lynx19gw_bms_dl_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->accumulator_current |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->accumulator_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accumulator_voltage |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->accumulator_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accumulator_so_c |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->accumulator_so_c |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accumulator_temp |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->accumulator_temp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_bms_dl_data_accumulator_current_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_dl_data_accumulator_current_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_dl_data_accumulator_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_dl_data_accumulator_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_dl_data_accumulator_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_dl_data_accumulator_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_dl_data_accumulator_so_c_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_dl_data_accumulator_so_c_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_dl_data_accumulator_so_c_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_bms_dl_data_accumulator_temp_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_bms_dl_data_accumulator_temp_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_bms_dl_data_accumulator_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_pel_pdo_1_rx_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_pel_pdo_1_rx_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->enable_drive_left, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_set_point_left, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_set_point_left, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_limit_left, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_limit_left, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->error_reset_left, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->error_reset_left, 8u, 0xffu);

    return (7);
}

int lynx19gw_nr_pel_pdo_1_rx_unpack(
    struct lynx19gw_nr_pel_pdo_1_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->enable_drive_left |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_set_point_left |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_set_point_left |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_limit_left |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_limit_left |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->error_reset_left |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->error_reset_left |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nr_pel_pdo_1_rx_enable_drive_left_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_pel_pdo_1_rx_enable_drive_left_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_1_rx_enable_drive_left_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_pel_pdo_1_rx_torque_set_point_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_pel_pdo_1_rx_torque_set_point_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_1_rx_torque_set_point_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_pel_pdo_1_rx_speed_limit_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_pel_pdo_1_rx_speed_limit_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_1_rx_speed_limit_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_pel_pdo_1_rx_error_reset_left_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_pel_pdo_1_rx_error_reset_left_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_pel_pdo_1_rx_error_reset_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_dl_sensors_3_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_sensors_3_t *src_p,
    size_t size)
{
    uint16_t acceleration_x;
    uint16_t acceleration_y;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    acceleration_x = (uint16_t)src_p->acceleration_x;
    dst_p[0] |= pack_left_shift_u16(acceleration_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(acceleration_x, 8u, 0xffu);
    acceleration_y = (uint16_t)src_p->acceleration_y;
    dst_p[2] |= pack_left_shift_u16(acceleration_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(acceleration_y, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->water_temp_1, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->water_temp_2, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->water_temp_3, 0u, 0xffu);

    return (7);
}

int lynx19gw_nr_dl_sensors_3_unpack(
    struct lynx19gw_nr_dl_sensors_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acceleration_x;
    uint16_t acceleration_y;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    acceleration_x = 0u;
    acceleration_x |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    acceleration_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->acceleration_x = (int16_t)acceleration_x;
    acceleration_y = 0u;
    acceleration_y |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    acceleration_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->acceleration_y = (int16_t)acceleration_y;
    dst_p->water_temp_1 |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->water_temp_2 |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->water_temp_3 |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int16_t lynx19gw_nr_dl_sensors_3_acceleration_x_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double lynx19gw_nr_dl_sensors_3_acceleration_x_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool lynx19gw_nr_dl_sensors_3_acceleration_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t lynx19gw_nr_dl_sensors_3_acceleration_y_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double lynx19gw_nr_dl_sensors_3_acceleration_y_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool lynx19gw_nr_dl_sensors_3_acceleration_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nr_dl_sensors_3_water_temp_1_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_3_water_temp_1_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_3_water_temp_1_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t lynx19gw_nr_dl_sensors_3_water_temp_2_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_3_water_temp_2_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_3_water_temp_2_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t lynx19gw_nr_dl_sensors_3_water_temp_3_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_3_water_temp_3_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_3_water_temp_3_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

int lynx19gw_nr_dl_sensors_2_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_sensors_2_t *src_p,
    size_t size)
{
    uint16_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->rotor_ambient_temp_l, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->rotor_ambient_temp_r, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->rotor_object_temp_l, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->rotor_object_temp_r, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->gear_box_temp_l, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->gear_box_temp_r, 0u, 0xffu);
    yaw = (uint16_t)src_p->yaw;
    dst_p[6] |= pack_left_shift_u16(yaw, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(yaw, 8u, 0xffu);

    return (8);
}

int lynx19gw_nr_dl_sensors_2_unpack(
    struct lynx19gw_nr_dl_sensors_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t yaw;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->rotor_ambient_temp_l |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rotor_ambient_temp_r |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->rotor_object_temp_l |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->rotor_object_temp_r |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->gear_box_temp_l |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->gear_box_temp_r |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    yaw = 0u;
    yaw |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    yaw |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->yaw = (int16_t)yaw;

    return (0);
}

uint8_t lynx19gw_nr_dl_sensors_2_rotor_ambient_temp_l_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_2_rotor_ambient_temp_l_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_rotor_ambient_temp_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nr_dl_sensors_2_rotor_ambient_temp_r_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_2_rotor_ambient_temp_r_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_rotor_ambient_temp_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nr_dl_sensors_2_rotor_object_temp_l_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_2_rotor_object_temp_l_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_rotor_object_temp_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nr_dl_sensors_2_rotor_object_temp_r_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_2_rotor_object_temp_r_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_rotor_object_temp_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nr_dl_sensors_2_gear_box_temp_l_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_2_gear_box_temp_l_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_gear_box_temp_l_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t lynx19gw_nr_dl_sensors_2_gear_box_temp_r_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nr_dl_sensors_2_gear_box_temp_r_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_gear_box_temp_r_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

int16_t lynx19gw_nr_dl_sensors_2_yaw_encode(double value)
{
    return (int16_t)(value);
}

double lynx19gw_nr_dl_sensors_2_yaw_decode(int16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_2_yaw_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nr_dl_sensors_1_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nr_dl_sensors_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->damper_rl, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->damper_rl, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->damper_rr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->damper_rr, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->wheel_speed_rl, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->wheel_speed_rl, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->wheel_speed_rr, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->wheel_speed_rr, 8u, 0xffu);

    return (8);
}

int lynx19gw_nr_dl_sensors_1_unpack(
    struct lynx19gw_nr_dl_sensors_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->damper_rl |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->damper_rl |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->damper_rr |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->damper_rr |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->wheel_speed_rl |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->wheel_speed_rl |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->wheel_speed_rr |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->wheel_speed_rr |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_nr_dl_sensors_1_damper_rl_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_dl_sensors_1_damper_rl_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_1_damper_rl_is_in_range(uint16_t value)
{
    return (value <= 6000u);
}

uint16_t lynx19gw_nr_dl_sensors_1_damper_rr_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nr_dl_sensors_1_damper_rr_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nr_dl_sensors_1_damper_rr_is_in_range(uint16_t value)
{
    return (value <= 6000u);
}

uint16_t lynx19gw_nr_dl_sensors_1_wheel_speed_rl_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double lynx19gw_nr_dl_sensors_1_wheel_speed_rl_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool lynx19gw_nr_dl_sensors_1_wheel_speed_rl_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nr_dl_sensors_1_wheel_speed_rr_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double lynx19gw_nr_dl_sensors_1_wheel_speed_rr_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool lynx19gw_nr_dl_sensors_1_wheel_speed_rr_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_nf_nr_sensors_1_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nf_nr_sensors_1_t *src_p,
    size_t size)
{
    uint8_t steering_angle;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->disk_temp_fl, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->disk_temp_fr, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake, 0u, 0xffu);
    steering_angle = (uint8_t)src_p->steering_angle;
    dst_p[3] |= pack_left_shift_u8(steering_angle, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->throttle, 0u, 0xffu);

    return (5);
}

int lynx19gw_nf_nr_sensors_1_unpack(
    struct lynx19gw_nf_nr_sensors_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t steering_angle;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->disk_temp_fl |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->disk_temp_fr |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    steering_angle = 0u;
    steering_angle |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->steering_angle = (int8_t)steering_angle;
    dst_p->throttle |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_nf_nr_sensors_1_disk_temp_fl_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_nr_sensors_1_disk_temp_fl_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_1_disk_temp_fl_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nf_nr_sensors_1_disk_temp_fr_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_nr_sensors_1_disk_temp_fr_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_1_disk_temp_fr_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t lynx19gw_nf_nr_sensors_1_brake_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_nr_sensors_1_brake_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_1_brake_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int8_t lynx19gw_nf_nr_sensors_1_steering_angle_encode(double value)
{
    return (int8_t)(value);
}

double lynx19gw_nf_nr_sensors_1_steering_angle_decode(int8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_1_steering_angle_is_in_range(int8_t value)
{
    return ((value >= -120) && (value <= 120));
}

uint8_t lynx19gw_nf_nr_sensors_1_throttle_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_nf_nr_sensors_1_throttle_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_1_throttle_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int lynx19gw_nf_nr_sensors_2_pack(
    uint8_t *dst_p,
    const struct lynx19gw_nf_nr_sensors_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->wheel_speed_fl, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->wheel_speed_fl, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->wheel_speed_fr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->wheel_speed_fr, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->damper_fl, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->damper_fl, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->damper_fr, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->damper_fr, 8u, 0xffu);

    return (8);
}

int lynx19gw_nf_nr_sensors_2_unpack(
    struct lynx19gw_nf_nr_sensors_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->wheel_speed_fl |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->wheel_speed_fl |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->wheel_speed_fr |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->wheel_speed_fr |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->damper_fl |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->damper_fl |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->damper_fr |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->damper_fr |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t lynx19gw_nf_nr_sensors_2_wheel_speed_fl_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double lynx19gw_nf_nr_sensors_2_wheel_speed_fl_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool lynx19gw_nf_nr_sensors_2_wheel_speed_fl_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nf_nr_sensors_2_wheel_speed_fr_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double lynx19gw_nf_nr_sensors_2_wheel_speed_fr_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool lynx19gw_nf_nr_sensors_2_wheel_speed_fr_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_nf_nr_sensors_2_damper_fl_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nf_nr_sensors_2_damper_fl_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_2_damper_fl_is_in_range(uint16_t value)
{
    return (value <= 6000u);
}

uint16_t lynx19gw_nf_nr_sensors_2_damper_fr_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_nf_nr_sensors_2_damper_fr_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_nf_nr_sensors_2_damper_fr_is_in_range(uint16_t value)
{
    return (value <= 6000u);
}

